name: My First workflow

on: [push]


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Welcome message
          run: echo "Hello, World! This is my first GitHub Actions workflow."

        - name: List files
          run: ls -la

        - name: Read file
          run: cat README.md