name: Generate ASCII Artwork

on: [push]


jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        ## Without Shell Script
        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Sleep for 30 sec
          run: sleep 30   

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON..... RAWR." >> dragon.txt
    
        - name: Upload File
          uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt

    Test_job:
        needs: Build_job
        runs-on: ubuntu-latest
        steps:
        - name: Download File
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact

        - name: Test File Existence
          run: |
            if [ -f dragon.txt ]; then
              echo "File dragon.txt exists."
            else
              echo "File dragon.txt does not exist."
              exit 1
            fi

        - name: Test File Existence using Grep
          run: grep -i "dragon" dragon.txt

    Deploy_job:
        needs: Test_job
        runs-on: ubuntu-latest
        steps:
        - name: Download File
          uses: actions/download-artifact@v3
          with:
            name: dragon-artifact

        - name: Display File Content
          run: cat dragon.txt

        - name: List files
          run: ls -la

        # - name: Execute Shell Script
        #   run: |
        #     chmod +x ./ascii.script.sh
        #     ./ascii.script.sh